### Use this file to test out your REST call before implementing them in the code

### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
@baseUrl = http://10.100.21.67:3000

### Request 1 : Get a member whose correct 'email' and 'password'
### Purpose   : To simulate the authentication process. 
GET {{baseUrl}}/members?email=alex&password=123x

### Request 2 : Get the list of events for a given member
### Purpose   : To render the main screen
GET {{baseUrl}}/events?member=2

### Request 3 : Create a new event for a given member
POST {{baseUrl}}/events
Content-Type: application/json

{
    "member": 2,
    "title": "A new event",
    "description": "This is a new event",
    "done": false
}

### Request 4 : Update the information of a given event
PUT {{baseUrl}}/events/6
Content-Type: application/json

{
    "member": 2,
    "title": "Updated title",
    "description": "Updated description",
    "done": false
}


### Request 5 : Delete a given event
DELETE {{baseUrl}}/events/6
