### Use this file to test out your REST call before implementing them in the code

### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
#@baseUrl = http://10.100.22.125:3000
@baseUrl = https://ppiconnect.herokuapp.com

### Getting the list of Member
GET {{baseUrl}}/member

###  Getting a Member of given matric
GET {{baseUrl}}/member/m1matric

### Request 1 : Get a member whose correct 'email' and 'password'
### Purpose   : To simulate the authentication process. 
GET {{baseUrl}}/member?email=todopsain11@gmail.com&password=m1password

### Getting the list of Event
GET {{baseUrl}}/event

###  Getting a Event of given id
GET {{baseUrl}}/event/1

### Request 3 : Create a new event
POST {{baseUrl}}/event
Content-Type: application/json

{
    "event_title": "e0title",
    "event_category": "Sport",
    "event_venue": "e0venue",
    "open_for": "Participants",
    "closed_on": "2021-04-03T16:00:00.000Z",
    "event_details": "e0details",
    "event_url": "https://form.typeform.com/to/bOOqUGlh?typeform-medium=embed-snippet",
    "event_date": "2021-05-04T16:00:00.000Z",
    "event_pic1": "e0pic1.PNG"
}

### Request 4 : Update the information of a given event
PATCH {{baseUrl}}/event/25
Content-Type: application/json

{
    "event_title": "e4title"
}


### Request 5 : Delete a given event
DELETE {{baseUrl}}/event/25
